version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - dupl
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: io/ioutil
              desc: use io and os packages instead
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gocyclo
        path: internal/*
      - linters:
          - lll
        path: api/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
