image:
  repository: ghcr.io/winrarr/operator-foundry
  tag: dev
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
leaderElection: true
enableHTTP2: false
healthProbeBindAddress: ":8081"

metrics:
  enabled: true
  port: 8443

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true

podAnnotations: {}
podLabels: {}
nodeSelector: {}
tolerations: []
affinity: {}
