{{- if and .Values.metrics.enabled .Values.metrics.secure .Values.metrics.readerRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-foundry.fullname" . }}-metrics-reader
  labels:
{{ include "operator-foundry.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{- end }}
