{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "operator-foundry.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.serviceMonitor.namespace }}
  labels:
{{ include "operator-foundry.labels" . | nindent 4 }}
{{- with .Values.metrics.serviceMonitor.labels }}
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "operator-foundry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: {{ ternary "https" "http" .Values.metrics.secure }}
    path: /metrics
    scheme: {{ ternary "https" "http" .Values.metrics.secure }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
{{- if .Values.metrics.secure }}
{{- with .Values.metrics.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ . }}
{{- end }}
    tlsConfig:
{{ toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 6 }}
{{- end }}
{{- with .Values.metrics.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.metrics.serviceMonitor.endpointAdditionalProperties }}
{{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}
