{{- if .Values.tenantAuthorRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-foundry.fullname" . }}-tenant-author
  labels:
{{ include "operator-foundry.labels" . | nindent 4 }}
rules:
- apiGroups:
  - patterns.operator-foundry.example
  resources:
  - patternresources
  - patternmemberships
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
