---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - patterns.operator-foundry.example
  resources:
  - patternconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - patterns.operator-foundry.example
  resources:
  - patternconnections/status
  - patternresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - patterns.operator-foundry.example
  resources:
  - patternresources
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - patterns.operator-foundry.example
  resources:
  - patternresources/finalizers
  verbs:
  - update
