apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-author-role
  labels:
    app.kubernetes.io/name: operator-foundry
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups:
  - patterns.operator-foundry.example
  resources:
  - patternresources
  - patternmemberships
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
