apiVersion: patterns.operator-foundry.example/v1alpha1
kind: PatternMembership
metadata:
  name: example-membership
  namespace: default
spec:
  connectionRef:
    name: example
  parentRef:
    name: example
  memberRef:
    name: example-member
  driftDetectionInterval: 5m
