apiVersion: patterns.operator-foundry.example/v1alpha1
kind: PatternResource
metadata:
  name: example
  namespace: default
spec:
  connectionRef:
    name: example
  value: desired
  creationPolicy: CreateOrAdopt
  deletionPolicy: Orphan
