apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metrics-scraping
  namespace: operator-foundry-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: operator-foundry
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
